version: '3.7'
services:
  cantaloupe:
    image: cantaloupe:latest
    build: ./cantaloupe
    ports:
      - 8182:8182
    user: root
    volumes:
      - /mnt/volume_nyc1_01/cantaloupe/data:/imageroot
      - /mnt/volume_nyc1_01/cantaloupe/cantaloupe.properties:/cantaloupe/cantaloupe.properties
    environment:
      ENDPOINT_ADMIN_SECRET: "${CANTALOUPE_SECRET}"
  nginx:
    container_name: nginx
    image: nginx
  postgresql:
    container_name: postgresql
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /mnt/volume_nyc1_01/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}