version: '3.7'
services:
  cantaloupe:
    image: cantaloupe:latest
    build: ./cantaloupe
    restart: always
    ports:
      - 8182:8182
    user: root
    volumes:
      - ${CANTALOUPE_DATA_DIR}:/imageroot
      - ./cantaloupe/cantaloupe.properties:/cantaloupe/cantaloupe.properties
    environment:
      ENDPOINT_ADMIN_SECRET: "${CANTALOUPE_SECRET}"
  nginx:
    container_name: nginx
    image: nginx
  postgresql:
    container_name: postgresql
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - postgres
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - postgresql
    networks:
      - postgres
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
       - ${PGADMIN_DATA_DIR}:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  hasura:
    container_name: hasura
    image: hasura/graphql-engine:v1.2.2
    restart: always
    depends_on:
      - postgresql
    networks:
      - postgres
    ports:
      - 8080:8080
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
networks:
  postgres:
    driver: bridge