version: '3.7'
services:
  cantaloupe:
    image: cantaloupe:latest
    build: ./cantaloupe
    ports:
      - 8182:8182
    user: root
    volumes:
      - ${CANTALOUPE_DATA_DIR}:/imageroot
      - ./cantaloupe/cantaloupe.properties:/cantaloupe/cantaloupe.properties
    environment:
      ENDPOINT_ADMIN_SECRET: "${CANTALOUPE_SECRET}"
    restart: always
  nginx:
    container_name: nginx
    image: nginx
  postgresql:
    container_name: postgresql
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - ${PGADMIN_DATA_DIR}:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped